version: "3.9"
services:
  postgres:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: hamburg_demo
      POSTGRES_USER: hamburg_demo
      POSTGRES_DB: hamburg_demo
    ports:
      - 5432:5432
  postgres_test:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: hamburg_demo_test
      POSTGRES_USER: hamburg_demo_test
      POSTGRES_DB: hamburg_demo_test
    ports:
      - 5433:5432
